#!/bin/sh
# Starts and stops CSR Key Storage daemon
#


case "$1" in
start)

    start-stop-daemon --start --exec /bin/ramsdsync

;;

stop)

    start-stop-daemon --stop --exec /bin/ramsdsync
;;

restart)
    $0 stop
    $0 start
;;

status)
    if pidof -o %PPID ramsdsync > /dev/null; then
        echo "Running"
        exit 0
    else
        echo "Not running"
        exit 1
    fi
;;

*)
    echo "Usage: $0 {start|stop|restart|status}"
    exit 1
esac
