#define EEPROM_EEPGD BIT7
#define EEPROM_CFGS BIT6

void EEPROM_get(UINT EEPROM_READ_ADDRESS,UCHAR Len,UCHAR *readbuffer);
void EEPROM_set(UINT EEPROM_WRITE_ADDRESS,UCHAR Len,UCHAR *writebuffer);
//UCHAR EEPROM_read_ONCE(UINT EEPROM_READ_ADDRESS_BYTE);
//void EEPROM_write_ONCE(UINT EEPROM_WRITE_ADDRESS_BYTE,UCHAR EEPROM_WRITE_BUF);
UCHAR SPCIfFirstRun(void);
