#include "stm32f1xx.h"
#include "stm32f103xe.h"
#include "common.h"

void ADC_Init()
{
    MODIFY_REG(ADC1->CR1, ADC_CR1_SCAN, 0);
    MODIFY_REG(ADC1->CR2, ADC_CR2_ALIGN, 0);
    MODIFY_REG(ADC12_COMMON->CR1, ADC_CR1_DUALMOD, 0);
    MODIFY_REG(ADC1->CR1, ADC_CR1_DISCEN | ADC_CR1_DISCNUM, 0);
    MODIFY_REG(ADC1->CR2, ADC_CR2_EXTSEL | ADC_CR2_CONT | ADC_CR2_DMA, ADC_CR2_EXTSEL_2 | ADC_CR2_EXTSEL_1 | ADC_CR2_EXTSEL_0);
    MODIFY_REG(ADC1->SQR1, ADC_SQR1_L, 0);
    MODIFY_REG(ADC1->SQR3, ADC_SQR3_SQ1, ADC_SQR3_SQ1_4);
    MODIFY_REG(ADC1->SMPR1, ADC_SMPR1_SMP16, ADC_SMPR1_SMP16);
    MODIFY_REG(ADC12_COMMON->CR2, ADC_CR2_TSVREFE, ADC_CR2_TSVREFE);

    tftprintf("CR1 %08x", ADC1->CR1);

    //SET_BIT(ADC1->CR2, ADC_CR2_RSTCAL);
    //while (ADC1->CR2 & ADC_CR2_RSTCAL);

    tftprintf("CR2 %08x", ADC1->CR2);

    //SET_BIT(ADC1->CR2, ADC_CR2_CAL);
    //while (ADC1->SR & ADC_CR2_CAL);

    tftprintf("SQR1 %08x", ADC1->SQR1);
    tftprintf("SQR3 %08x", ADC1->SQR3);
    tftprintf("SMPR1 %08x", ADC1->SMPR1);

    tftprintf("APB2ENR %08x", RCC->APB2ENR);
    tftprintf("CFGR %08x", RCC->CFGR);
}
